import express from "express";
import path from "path";
import { fileURLToPath } from "url";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());

  // Lazy initialize Gemini client
  let aiClient: GoogleGenAI | null = null;
  function getAiClient() {
    if (!aiClient) {
      const apiKey = process.env.GEMINI_API_KEY;
      if (!apiKey || apiKey === "MY_GEMINI_API_KEY") {
        console.warn("GEMINI_API_KEY environment variable is not configured correctly.");
      }
      aiClient = new GoogleGenAI({
        apiKey: apiKey || "",
        httpOptions: {
          headers: {
            "User-Agent": "aistudio-build",
          },
        },
      });
    }
    return aiClient;
  }

  // --- API Routes ---

  // Health check
  app.get("/api/health", (req, res) => {
    res.json({ status: "ok", timestamp: new Date().toISOString() });
  });

  // AI Diagnostic Copilot Endpoint
  app.post("/api/gemini/diagnose", async (req, res) => {
    try {
      const { vehicleModel, symptoms, obdCode } = req.body;

      if (!symptoms && !obdCode) {
        return res.status(400).json({ error: "Please provide vehicle symptoms or an OBD-II code." });
      }

      const ai = getAiClient();
      const vehicleInfo = vehicleModel ? `para um ${vehicleModel}` : "para um veículo";
      const prompt = `Faça um diagnóstico mecânico virtual ${vehicleInfo}.
Sintomas descritos pelo cliente: "${symptoms || "Nenhum especificado"}"
Código de Falha OBD-II (se houver): "${obdCode || "Nenhum especificado"}"

Forneça um relatório de diagnóstico profissional, detalhado e estruturado. O texto deve ser inteiramente redigido em Português do Brasil (PT-BR).`;

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "Você é um mecânico mestre de elite e especialista em diagnósticos automotivos. Você analisa sintomas e códigos de falha OBD-II para fornecer avaliações altamente precisas, passos de solução de problemas e estimativas em PORTUGUÊS DO BRASIL.",
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.OBJECT,
            properties: {
              summary: {
                type: Type.STRING,
                description: "Um resumo detalhado do que provavelmente está acontecendo com o veículo (em Português).",
              },
              severity: {
                type: Type.STRING,
                description: "Nível de gravidade operacional e de segurança. Deve ser 'Low', 'Medium' ou 'High' para compatibilidade de sistema.",
              },
              possibleCauses: {
                type: Type.ARRAY,
                description: "Lista das 3 principais causas raiz prováveis.",
                items: {
                  type: Type.OBJECT,
                  properties: {
                    title: { type: Type.STRING, description: "Nome da causa em português (ex: Sensor de O2 Defeituoso)" },
                    description: { type: Type.STRING, description: "Descrição detalhada de como essa causa leva ao sintoma (em português)." },
                    urgency: { type: Type.STRING, description: "Urgência de ação em português (ex: Ação Imediata, Inspecionar Breve, Monitorar)" },
                  },
                  required: ["title", "description", "urgency"],
                },
              },
              diagnosticSteps: {
                type: Type.ARRAY,
                description: "Guia passo a passo de diagnóstico para isolar o problema (em português).",
                items: { type: Type.STRING },
              },
              estimatedTime: {
                type: Type.STRING,
                description: "Tempo estimado de mão de obra para diagnóstico e reparo em português (ex: '1.5 - 2.5 horas').",
              },
              suggestedParts: {
                type: Type.ARRAY,
                description: "Peças de reposição ou consumíveis sugeridos em português (ex: ['Pastilhas de Freio Dianteiras', 'Fluido de Freio DOT4']).",
                items: { type: Type.STRING },
              },
            },
            required: ["summary", "severity", "possibleCauses", "diagnosticSteps", "estimatedTime", "suggestedParts"],
          },
        },
      });

      const responseText = response.text;
      if (!responseText) {
        throw new Error("No response content generated by Gemini.");
      }

      const data = JSON.parse(responseText.trim());
      res.json(data);
    } catch (error: any) {
      console.error("Gemini Diagnostic Error:", error);
      res.status(500).json({
        error: "Diagnostic analysis failed.",
        details: error.message || "An unexpected error occurred during analysis.",
      });
    }
  });

  // AI Customer Communications Draft Endpoint
  app.post("/api/gemini/communicate", async (req, res) => {
    try {
      const { jobTitle, currentStatus, details, tone } = req.body;

      if (!jobTitle || !currentStatus) {
        return res.status(400).json({ error: "Missing required jobTitle or currentStatus fields." });
      }

      const ai = getAiClient();
      const prompt = `Escreva uma mensagem de atualização de serviço para um cliente sobre a manutenção do seu veículo.
Nome do Serviço: "${jobTitle}"
Status Atual: "${currentStatus}"
Detalhes Técnicos/Trabalho realizado: "${details || "Verificação padrão concluída"}"
Tom de Comunicação Solicitado: "${tone || "Profissional"}"

Mantenha o rascunho conciso, educado, fácil de entender para um proprietário de carro não técnico e tranquilizador. Sempre termine com uma assinatura profissional padrão da nossa oficina. Escreva o texto INTEIRAMENTE EM PORTUGUÊS DO BRASIL. Não inclua cabeçalhos em markdown, apenas o corpo do texto da mensagem.`;

      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: prompt,
        config: {
          systemInstruction: "Você é um Consultor de Serviços Automotivos excepcional, excelente em traduzir jargões mecânicos técnicos complexos em comunicações claras, tranquilizadoras e de alta confiança para proprietários de veículos em PORTUGUÊS DO BRASIL.",
        },
      });

      const draft = response.text || "";
      res.json({ draft: draft.trim() });
    } catch (error: any) {
      console.error("Gemini Communication Error:", error);
      res.status(500).json({
        error: "Failed to generate communication draft.",
        details: error.message || "An unexpected error occurred.",
      });
    }
  });

  // --- Serve Frontend ---

  if (process.env.NODE_ENV !== "production") {
    console.log("Starting server in DEVELOPMENT mode (with Vite middleware)...");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    console.log("Starting server in PRODUCTION mode...");
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on port ${PORT}`);
    console.log(`Available local URL: http://localhost:${PORT}`);
  });
}

startServer();
